# Generated by Django 3.1.4 on 2020-12-23 14:40

from django.db import migrations
import json


class Migration(migrations.Migration):


    def copy_moscow_legends_to_places(apps, schema_editor):
#       copy_json_to_places(apps, schema_editor, 'static/places/moscow_legends.json')
        json_file = 'static/places/moscow_legends.json'
        Place = apps.get_model('places', 'Place')
        with open(json_file) as file:
            data = json.loads(file.read())
            Place.objects.get_or_create(
                title=data['title'],
                description_short=data['description_short'],
                description_long=data['description_long'],
                lat=data['coordinates']['lat'],
                lng=data['coordinates']['lng']
            )


    def copy_roofs24_to_places(apps, schema_editor):
#        copy_json_to_places(apps, schema_editor, 'static/places/roofs24.json')
        json_file = 'static/places/roofs24.json'
        Place = apps.get_model('places', 'Place')
        with open(json_file) as file:
            data = json.loads(file.read())
            Place.objects.get_or_create(
                title=data['title'],
                description_short=data['description_short'],
                description_long=data['description_long'],
                lat=data['coordinates']['lat'],
                lng=data['coordinates']['lng']
            )


    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
         migrations.RunPython(copy_moscow_legends_to_places),
         migrations.RunPython(copy_roofs24_to_places),
    ]
