# Generated by Django 3.1.4 on 2021-01-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20201224_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['number']},
        ),
        migrations.AddField(
            model_name='image',
            name='number',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0, primary_key=True, serialize=False, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to='images', verbose_name='Изображение проекта'),
        ),
    ]
